api_gateway:
  - api:
      name: "core-api"
      methods:
        - http_method: "GET"
          authorization: "NONE"
        - http_method: "POST"
          authorization: "AWS_IAM"
      integrations:
        - http_method: "GET"
          integration_http_method: "POST"
          type: "HTTP_PROXY"
          uri: "arn:aws:lambda:region:account-id:function:function-name"
          connection_type: "VPC_LINK"
          connection_id: "vpc-link-id"
        - http_method: "POST"
          integration_http_method: "POST"
          type: "AWS"
          uri: "arn:aws:apigateway:region:sqs:path/queue-name"
          connection_type: "VPC_LINK"
          connection_id: "vpc-link-id"
