ecs:
  - vpc_id: "vpc-00c93211486e5634d"
    subnet_ids:
      - "subnet-051d912881d32fd63"
      - "subnet-06774db1a3ef23d14"
    app_name: "my-rnt-app"
    log_retention_in_days: 30
    cluster_id: "my-cluster-id"
    cluster_name: "my-cluster"
    desired_count: 2
    launch_type: "FARGATE"
    nlb_type: "network"
    container_port: 8080
    api_nlb_name: "rnt-api-nlb"
    security_group_ids:
      - "sg-12345"
      - "sg-67890"
    lb_listener: "listener-12345"
    assign_public_ip: true
    share_tgw: false
    ecs_task_execution_role_name: "ecsTaskExecutionRole"
    aws_sns_topic_alarm_topic_arn: "arn:aws:sns:us-east-1:123456789012:alarm-topic"
    vpc_endpoints:
        - vpc_id: "vpc-00c93211486e5634d"
          vpc_endpoint_type: "Interface"
          service_name: "com.amazonaws.us-east-1.ecr.api"
          subnet_ids:
            - "subnet-051d912881d32fd63"
            - "subnet-06774db1a3ef23d14"
          security_group_ids:
            - "sg-12345"
            - "sg-67890"
        - vpc_id: "vpc-00c93211486e5634d"
          vpc_endpoint_type: "Interface"
          service_name: "com.amazonaws.us-east-1.ecr.dkr"
          subnet_ids:
            - "subnet-051d912881d32fd63"
            - "subnet-06774db1a3ef23d14" 
    task_definition:
      task_cpu: 256
      task_memory: 512
      host_port: 8080
      ecs_task_execution_role_arn: "arn:aws:iam::123456789012:role/ecsTaskExecutionRole"
      log_group_region: "us-east-1"
    aws_lb_target_group:
      port: 80
      protocol: "TCP"
      target_type: "ip"
      health_check:
        enabled: true
        interval: 30
        path: "/"
        protocol: "HTTP"
        timeout: 5
        healthy_threshold: 2
        unhealthy_threshold: 2
        matcher: "200"
    aws_lb_listener:
      load_balancer_arn: "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/my-lb/1234567890"
      protocol: "TCP"
      port: "80"
